In [1]:
import numpy as np

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

data = np.random.randn(7,4)

names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [2]:
data

array([[-0.12268905,  1.20605387,  0.64732986, -0.85554684],
       [-0.2727452 , -2.00525227, -0.0576535 , -0.14395788],
       [-1.05149461, -1.95032004,  1.00623163, -0.59866807],
       [ 0.15107784, -0.00666366, -0.45477243,  1.11323573],
       [ 0.87469634, -0.2773426 ,  1.31299062,  1.46861128],
       [ 0.23682372,  0.00722236,  0.56935802, -1.45743535],
       [-1.02380311, -0.46480518,  0.08775381,  1.23152821]])

In [3]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [4]:
data[names == "Bob"]

array([[-0.12268905,  1.20605387,  0.64732986, -0.85554684],
       [ 0.15107784, -0.00666366, -0.45477243,  1.11323573]])

In [5]:
data[names == "Bob", 2:]

array([[ 0.64732986, -0.85554684],
       [-0.45477243,  1.11323573]])

In [6]:
data[names == "Bob", 3]

array([-0.85554684,  1.11323573])

In [7]:
names != "Bob"

array([False,  True,  True, False,  True,  True,  True])

In [8]:
data[~(names == "Bob")]

array([[-0.2727452 , -2.00525227, -0.0576535 , -0.14395788],
       [-1.05149461, -1.95032004,  1.00623163, -0.59866807],
       [ 0.87469634, -0.2773426 ,  1.31299062,  1.46861128],
       [ 0.23682372,  0.00722236,  0.56935802, -1.45743535],
       [-1.02380311, -0.46480518,  0.08775381,  1.23152821]])

In [9]:
data[names != "Bob"]

array([[-0.2727452 , -2.00525227, -0.0576535 , -0.14395788],
       [-1.05149461, -1.95032004,  1.00623163, -0.59866807],
       [ 0.87469634, -0.2773426 ,  1.31299062,  1.46861128],
       [ 0.23682372,  0.00722236,  0.56935802, -1.45743535],
       [-1.02380311, -0.46480518,  0.08775381,  1.23152821]])

In [10]:
mask = (names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [12]:
data

array([[-0.12268905,  1.20605387,  0.64732986, -0.85554684],
       [-0.2727452 , -2.00525227, -0.0576535 , -0.14395788],
       [-1.05149461, -1.95032004,  1.00623163, -0.59866807],
       [ 0.15107784, -0.00666366, -0.45477243,  1.11323573],
       [ 0.87469634, -0.2773426 ,  1.31299062,  1.46861128],
       [ 0.23682372,  0.00722236,  0.56935802, -1.45743535],
       [-1.02380311, -0.46480518,  0.08775381,  1.23152821]])

In [11]:
data[mask]

array([[-0.12268905,  1.20605387,  0.64732986, -0.85554684],
       [-1.05149461, -1.95032004,  1.00623163, -0.59866807],
       [ 0.15107784, -0.00666366, -0.45477243,  1.11323573],
       [ 0.87469634, -0.2773426 ,  1.31299062,  1.46861128]])

## Fancy indexing

In [16]:
arr = np.empty((8,4))

for item in range(8):
  arr[item] = item
  
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [14]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [15]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [17]:
arr = np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [18]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])